### ISSUE TITLE
Problem to switch from the Gitlab code to the Github code

### ISSUE THREAD

**Issue by pedrowunsch27** [ctu-mrs/uav_core#14]
Good evening,

I have been working with your entire software architecture for a couple of months, trying to implement a Distributed Reference governor using the usefull tools MRS provides. The software I was using was the one that was available on your Gitlab, before you removed it and turned it into a Github repository. I was still working on your original code until last week when my computer crashed. I had saved the additional files that I made in a personal drive but they are sadly not compatible with the new version of your code. I have tried to adapt it but I keep having many problems that I didn't have before. Would there be a way I could have access to the previous version of your code ( the one from Gitlab) ? I am a student working for my supervisor Bryan Convens who had access to your Gitlab. Thank you in advance for your help. 

Best regards, 

Pedro Wunsch

**Comment by klaxalk** [comment]
Hey Pedro,

yes, we have the old stuff backed up, however, there is nothing "more" there than there it is here on Github. The Github repositories contain our Gitlab history. Actually, our last commit of the _uav_core_ repo on Gitlab is e4e56c2b, which you can find here on Github as well. I would recommend updating your code to work with the new version since it is more "future proof". It is unlikely that the pre-open-sourcing version from Gitlab will work with a fresh installation of your OS (outside dependencies such as Mavros often cause us troubles). I bet the automatic installation would not work now either. Moreover:
- we can't give you support for the old version,
- the open-source version is better documented (the old had hardly any documentation),
- the open-source version got a lot of problems and quirks figured out (we got a lot of time for it during the quarantine),
- the new open-source version got a lot of time invested in just to be easier to read and understand, thus, it is much easier to borrow code from it. It is not universal, there are still some botched pieces here, but much less than before.

There are some changes that happened during the open-sourcing era, that might influence normal people:
- the way how we send the desired trajectory to the system: the message type changed to [topic](https://ctu-mrs.github.io/mrs_msgs/msg/TrajectoryReference.html), [service](https://ctu-mrs.github.io/mrs_msgs/srv/TrajectoryReferenceSrv.html), the topic/service address is _control_manager/trajectory_reference_
- our paramLoader and other tools from mrs_lib slightly changed API, see https://github.com/ctu-mrs/mrs_lib

If you are lost with some particular stuff, don't hesitate to contact us here with the problem, we can suggest what to do. Also, feel free to check our own code for inspiration on how we do stuff in the new system.

Sincerely,
Tomas
