### ISSUE TITLE
Using ROS1 bridge

### ISSUE THREAD

**Issue by maxhofidrone** [ctu-mrs/uav_core#52]
Dear MRS-Team,
I have to use ROS2 on a MRS-UAV system. Therefore, I want to use the ROS1 bridge to access the necessary mrs-topics within ROS2. I found following [installation script](https://github.com/ctu-mrs/uav_core/blob/master/installation/ros2/02_build_rosbridge.sh) in your repo. I changed the ROS _galaxy_ references to _foxy_ and ran the script. Unfortunatelly it does not finish the build process due to following error:
![image](https://github.com/ctu-mrs/uav_core/assets/55589716/8cdd8954-0a8e-4179-ae99-b591edf96c0b)

Is the current ROS1 noetic MRS-System compatible with the ROS 1 bridge? I got the same error when using the [official tutorial ](https://github.com/ros2/ros1_bridge) for using the ROS 1 bridge. For me it seems a problem with the custom TF2 library shipped with the MRS-System.

I further saw that there are additional colcon related aliases where set up in [shell_additions.sh](https://github.com/ctu-mrs/uav_core/blob/450657746c90dfec5ace71206d83e96690f64e02/miscellaneous/shell_additions/shell_additions.sh#L516). Do these still work with noetic as intended?

Thank you very much  in advance and best regards,

Max

**Comment by klaxalk** [comment]
Hey, the last time we tried, it was not compatible. The bridge compilation used to fail due to bugs (reasons listed here https://github.com/ctu-mrs/ros2_examples), but that is already 2 years ago. It might be possible that you will succeed now. However, the necessary condition would be to have the mrs_msgs for ROS2 (https://github.com/ctu-mrs/mrs_msgs/tree/ros2) in a state compatible with the current ROS1 master branch, which it is not. So if you intend to interface the MRS System with ROS2, I would not suggest building a custom node with ROS<->ROS2 connection that will manage the translation to ROS2 for you, without relying on mrs_msgs.

**Comment by klaxalk** [comment]
But if your only problem is the tf2 library, just delete/CATKIN_IGNORE it form the MRS System. We only have a small quality-of-life patch there which is not necessary to have (just a warning suppression).
